using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace IrcSharp.SourceGenerators;

[Generator]
public class EventArgsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var ircSharpEvents = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "IrcSharp.Attributes.IrcSharpEventAttribute",
                predicate: (node, _) => node is ClassDeclarationSyntax,
                transform: (syntaxContext, _) =>
                {
                    var attributeDataLst = syntaxContext.Attributes
                        .Where(x => x.AttributeClass?.ToDisplayString() == "IrcSharp.Attributes.IrcSharpEventAttribute")
                        .ToList();

                    var attributes = new List<AttributeData>();
                    
                    foreach (var attributeData in attributeDataLst)
                    {
                        if (attributeData.ConstructorArguments.Length < 1)
                        {
                            // invalid attribute to be ignored
                            continue;
                        }

                        var eventName = attributeData.ConstructorArguments[0].Value?.ToString();
                        if (eventName is null)
                        {
                            // invalid attribute to be ignored
                            continue;
                        }

                        if (attributeData.ConstructorArguments is [_, { Values.Length: 0 } _])
                        {
                            attributes.Add(AttributeData.Create(eventName, null));
                            continue;
                        }

                        var parameters = attributeData
                            .ConstructorArguments[1]
                            .Values
                            .Where(x => x.Value is not null)
                            .Select(x => x.Value!.ToString())
                            .Where(x => !string.IsNullOrWhiteSpace(x))
                            .ToArray();
                        
                        attributes.Add(AttributeData.Create(eventName, parameters!));
                    }

                    return attributes;
                })
            .SelectMany(static (x, _) => x);

        context.RegisterSourceOutput(ircSharpEvents.Collect(), static (spc, source) => GenerateEvent(spc, source));
    }

    private static void GenerateEvent(SourceProductionContext spc, ImmutableArray<AttributeData> source)
    {
        /*
         * // <auto-generated/>
         * #nullable enable
         *
         * namespace IrcSharp.Events;
         *
         * public partial sealed class {Name}EventArgs : EventArgs
         * {
         *   ## IF EMPTY PARAMETERS ##
         *   public static readonly {Name}EventArgs Instance = new();
         *   private {Name}EventArgs() {}
         * 
         *   ## ELSE ##
         *   ### LOOP ### -> {ParamterType} ; {ParameterName} on {Parameters}
         *   public required {ParameterType} {ParameterName} {{ get; init; }}
         *   ### ENDLOOP ###
         *
         *   public static {Name}EventArgs Create(
         *   ### LOOP (not last element) ### -> {ParameterType} {ParameterName}
         *     {ParameterType} {ParameterName:camelCaseFormat},
         *   ### ENDLOOP ###
         *     {LastParameterType} {LastParameterName:camelCaseFormat})
         *   {
         *     return new {Name}EventArgs
         *     {
         *       ### LOOP (not last element) ### -> {ParameterType} {ParameterName}
         *       {ParameterName} = {ParameterName:camelCaseFormat},
         *       ### ENDLOOP ###
         *       {LastParameterName} = {LastParameterName:camelCaseFormat}  
         *     };
         *   }
         * }
         */

        if (source.IsDefaultOrEmpty)
        {
            return;
        }

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace IrcSharp.Events;");
        builder.AppendLine();

        foreach (var @event in source)
        {
            builder.AppendLine($"public partial class {@event.EventName}EventArgs : EventArgs");
            builder.AppendLine("{");

            if (@event.Parameters is null or { Length: 0 })
            {
                builder.AppendLine($"    public static readonly {@event.EventName}EventArgs Instance = new();");
                builder.AppendLine($"    private {@event.EventName}EventArgs() {{}}");
            }
            else
            {
                // generate the properties
                foreach (var (parameterType, parameterName) in @event.Parameters)
                {
                    builder.AppendLine($"    public required {parameterType} {parameterName} {{ get; init; }}");
                }
                
                builder.AppendLine();
                
                // generate the factory method
                builder.AppendLine($"    public static {@event.EventName}EventArgs Create(");
                for (var index = 0; index < @event.Parameters.Length; index++)
                {
                    var (parameterType, parameterName) = @event.Parameters[index];
                    
                    var lowerFirstChar = char.ToLowerInvariant(parameterName[0]);
                    var restPropertyName = parameterName[1..];
                    var camelCasePropertyName = $"{lowerFirstChar}{restPropertyName}";
                    
                    builder.Append($"        {parameterType} {camelCasePropertyName}");
                    builder.AppendLine(index < @event.Parameters.Length - 1 ? "," : ")");
                }

                builder.AppendLine("    {");
                builder.AppendLine($"        return new {@event.EventName}EventArgs");
                builder.AppendLine("        {");
                for (var index = 0; index < @event.Parameters.Length; index++)
                {
                    var (_, parameterName) = @event.Parameters[index];
                    
                    var lowerFirstChar = char.ToLowerInvariant(parameterName[0]);
                    var restPropertyName = parameterName[1..];
                    var camelCasePropertyName = $"{lowerFirstChar}{restPropertyName}";

                    builder.Append($"            {parameterName} = {camelCasePropertyName}");
                    if (index < @event.Parameters.Length - 1)
                    {
                        builder.AppendLine(",");
                    }
                    else
                    {
                        builder.AppendLine();
                    }
                }

                builder.AppendLine("        };");
                builder.AppendLine("    }");
            }
            
            builder.AppendLine("}");
            builder.AppendLine();
        }
        
        spc.AddSource("IrcSharpEvents.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }
}

internal sealed record AttributeData(string EventName, (string Type, string ParameterName)[]? Parameters)
{
    public static AttributeData Create(string eventName, string[]? parameterNames)
    {
        return new AttributeData(eventName, parameterNames?.Select(x =>
        {
            var splittedParameter = x.Split(':');
            return (splittedParameter[0], splittedParameter[1]);
        }).ToArray());
    }
}